---
- include: install.yml
  tags: install
  when: ansible_os_family != "RedHat"

- include: install-centos.yml
  tags: install
  when: ansible_os_family == "RedHat"

- include: configure.yml
  tags: configure
  when: ansible_os_family != "RedHat"

- include: configure-centos.yml
  tags: configure
  when: ansible_os_family == "RedHat"

- include: secure.yml
  tags: secure

- include: databases.yml
  tags: databases

- include: users.yml
  tags: users
