---
- hosts: all

  pre_tasks:
    - name: Install required dependencies when running ansible with python3
      raw: apt -y update && apt install -y python3-apt
      when:
        - ansible_os_family == 'Debian'
        - ansible_python_interpreter is defined and ansible_python_interpreter == '/usr/bin/python3'

    - name: Ensure build dependencies are installed (Debian)
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - unzip
        - tar
        - sudo
      when: ansible_os_family == 'Debian'

    - name: Include vars
      include_vars: "test_role_vars.yml"

  roles:
    - role_under_test